sensors:
  front:
    trigger: 11
    echo: 8
    max_distance: 4
motors:
  - name: right
    enable: 4
    pin1: 15
    pin2: 14
  - name: left
    enable: 17
    pin1: 27
    pin2: 18
servos:
  11:
    name: camera
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -58
      max: 9
  12:
    name: shoulder
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 90
  13:
    name: elbow
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 63
  14:
    name: wrist
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 90
  15:
    name: gripper
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 4
leds:
  type: pixelstrip
  pin: 12
  count: 16
  frequency: 800000
  dma: 10
  invert: False
  channel: 0
  brightness: 255
  names:
    0: left1
    1: left2
    2: left3
    4: left4
    5: left6
    6: right1
    7: right2
    8: right3
    9: right4
    10: right5
    11: right6