distancesensors:
  front:
    trigger: 11
    echo: 8
    max_distance: 4
linesensors:
  left:
    pin: 20
  midle:
    pin: 16
  right:
    pin: 19
motors:
  - name: right
    enable: 4
    pin1: 15
    pin2: 14
  - name: left
    enable: 17
    pin1: 27
    pin2: 18
servos:
  11:
    name: camera
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -58
      max: 9
  12:
    name: shoulder
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 90
  13:
    name: elbow
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 63
  14:
    name: wrist
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 90
  15:
    name: gripper
    pwm:
      min: 100
      max: 500
    angle:
      range: 180
      min: -90
      max: 4
leds:
  type: pixelstrip
  pin: 12
  count: 16
  frequency: 800000
  dma: 10
  invert: False
  channel: 0
  brightness: 255
  names:
    0: left_bottom_back
    1: left_bottom_middle
    2: left_bottom_front
    3: left_top_back
    4: left_top_middle
    5: left_top_front
    6: right_top_back
    7: right_top_middle
    8: right_top_front
    9: right_bottom_back
    10: right_bottom_middle
    11: right_bottom_front